// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD41lFNw1pionqugcTpLZrH_x2TwJPgToU',
    appId: '1:922307492010:web:6e7f9fa675e05174d3f8d3',
    messagingSenderId: '922307492010',
    projectId: 'flutter-dbestech',
    authDomain: 'flutter-dbestech.firebaseapp.com',
    storageBucket: 'flutter-dbestech.appspot.com',
    measurementId: 'G-39TFDWERP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXdYAOtClRGqB6YhNtfe_aQ0xJcvUrH6Q',
    appId: '1:922307492010:android:a07f646b9eb6dffcd3f8d3',
    messagingSenderId: '922307492010',
    projectId: 'flutter-dbestech',
    storageBucket: 'flutter-dbestech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK0TOFYKtA_bw2Z9--K42KuCnF61MZczE',
    appId: '1:922307492010:ios:0a515abc40b83287d3f8d3',
    messagingSenderId: '922307492010',
    projectId: 'flutter-dbestech',
    storageBucket: 'flutter-dbestech.appspot.com',
    iosBundleId: 'com.example.dbestech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD41lFNw1pionqugcTpLZrH_x2TwJPgToU',
    appId: '1:922307492010:web:59d89cb52ff8f86dd3f8d3',
    messagingSenderId: '922307492010',
    projectId: 'flutter-dbestech',
    authDomain: 'flutter-dbestech.firebaseapp.com',
    storageBucket: 'flutter-dbestech.appspot.com',
    measurementId: 'G-P62RDEWSGM',
  );
}
